### ISSUE TITLE
nether compatibility

### ISSUE THREAD

**Issue by mckaygerhard** [taikedz-mt/nssb#1]
i read the code and i started a dedicated server for NSSM at subs.fusilsystem.com but now i want to use neteher and modenlor so the solution by me is to read the setting of nether line deep and if are so deep raised an error to force to admin to propérty configure..

this is based on that mordenlor are build at fixed deep and nether can be much more higer to do not conflict

of course this need a status of this repository and a welcome from you @taikedz @taikedz-mt to analize the PR sends

**Comment by taikedz** [comment]
Hi - I'm not entirely sure what you want me to do here...

There are several mods that use depth to add a secondary or extra world, including Nether and EtherealCaves (the only two that I'm aware of apart from NSSB). There could be others, now, or in the future, and trying to support each mod explicitly in the base NSSB mod is not something I would want to do, unless you can show me a truly general-purpose solution.

In general, these deep-realms mods are to be considered incompatible, and as such I feel it is up to the server admin who is choosing their mods to know what they're doing.

It could be possible to add a change to actually turn off the terrain generation for Morlendor, whilst keeping its mobs and blocks - but those would only then be available in Creative Mode, which makes little sense as a result.

**Comment by mckaygerhard** [comment]
.. i am talking about that both can coexist we just generated one at one level (by example y = 25000 for mordenlor) and the other at another level (by example nether at 10000 as maximun) so both can generate terrain without conflicts? in fact nether can be customized to generate the terrain at any level if configured

**Comment by mckaygerhard** [comment]
@taikedz  now complete checked the mod, noted it assume the layer -30000 is available even if the main minetest.conf file pointed is lower or different,

maybe it must take the max from the minetest.conf but due that there's no conflicts with "nether" cos the nether can be configured to be less deep above -25000, and plese revised my two PR that fixed so many problems

**Comment by mckaygerhard** [comment]
implemented at https://notabug.org/TenPlus1/nssb/commit/ee84ab559ea16a09053c26f3d46fc61e90819e3b i will close cos i will put a new merge request about it..
